apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: default
  labels:
    app: {{ .Values.appName }}
data:
  MYSQL_DATABASE: {{ .Values.mysqlDatabase }}
  MYSQL_USER: {{ .Values.mysqlUser }}
