apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: {{ .Values.mysqlTier}}
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: {{ .Values.mysqlTier }}
  type: ClusterIP