apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-configmap
  namespace: default
  labels:
    app: {{ .Values.appName }}
data:
  WORDPRESS_DB_HOST: {{ .Values.wordpressDbhost }}
  WORDPRESS_DB_NAME: {{ .Values.mysqlDatabase}}
  WORDPRESS_DB_USER: {{ .Values.wordpressDbuser }}
