apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  labels:
    type: local
spec:
  storageClassName: wordpress-storage-class
  capacity:
    storage: {{ .Values.wordpressvolumeSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/wordpress