apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      tier: {{ .Values.wpTier }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        tier: {{ .Values.wpTier }}
    spec:
      containers:
      - image: {{ .Values.wordpressImage }}
        name: {{ .Values.appName }}
        env:
        - name: WORDPRESS_DB_HOST  # CONFIGMAP REFERENCE
          valueFrom:
            configMapKeyRef:
              name: wordpress-configmap
              key: WORDPRESS_DB_HOST
        - name: WORDPRESS_DB_NAME  # CONFIGMAP REFERENCE
          valueFrom:
            configMapKeyRef:
              name: wordpress-configmap
              key: WORDPRESS_DB_NAME
        - name: WORDPRESS_DB_PASSWORD  # SECRET REFERENCE
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: WORDPRESS_DB_USER  # CONFIGMAP REFERENCE
          valueFrom:
            configMapKeyRef:
              name: wordpress-configmap
              key: WORDPRESS_DB_USER
        - name: WORDPRESS_DEBUG
          value: "1"
        ports:
        - containerPort: {{ .Values.wordpressPort }}
          name: {{ .Values.appName }}
        volumeMounts:
        - name: {{ .Values.wordpressVolume }}
          mountPath: {{ .Values.wordpressMountpath }}
      volumes:
      - name: {{ .Values.wordpressVolume }}
        persistentVolumeClaim:
          claimName: {{ .Values.wordpresspersistentVolumeClaim }}